spring:
 application:
  name: eureka-registry-lb-demo
  
server:
      port: 8761
    
eureka:
  client:
  #you don't register the Service Discovery in the Service Discovery!
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0


